name: Gitee Async
on:
  workflow_dispatch:
  # page_build:
  schedule: [ cron: '30 9 * * *' ]
# #     - cron: '00 04 * * *' # once a day at 04:00 UTC / 12:00 BeiJing
# #     - cron: '05 04 * * *' # once a day at 04:05 UTC / 12:05 BeiJing
# #     - cron: '00 07 * * *' # once a day at 07:00 UTC / 15:00 BeiJing
# #     - cron: '05 07 * * *' # once a day at 07:05 UTC / 15:05 BeiJing
# #     - cron: '30 09 * * *' # once a day at 07:05 UTC / 17:30 BeiJing

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Sync to Gitee
      #   uses: wearerequired/git-mirror-action@master
      #   env:
      #     # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      #     SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      #   with:
      #     # 注意替换为你的 GitHub 源仓库地址
      #     source-repo: git@github.com:doocs/leetcode.git
      #     # 注意替换为你的 Gitee 目标仓库地址
      #     destination-repo: git@gitee.com:Doocs/leetcode.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: biwangwang
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: Stock_Screener
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main
          directory: docs 
          https: false

